services:
  - type: web
    name: optimizacion-inventario-api
    env: python
    plan: free
    branch: main

    workingDirectory: backend     # <<-- Debe estar exactamente aquí

    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt

    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    healthCheckPath: /
