services:
  - type: web
    name: optimizacion-inventario-api
    env: python
    plan: free
    branch: main

    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements-root.txt

    startCommand: |
      cd backend
      uvicorn main:app --host 0.0.0.0 --port $PORT

    healthCheckPath: /
