# render.yaml

services:
  - type: web
    name: optimizacion-inventario-api
    env: python
    plan: free
    branch: main

    # --------------------------------------------------
    # 1) Trabajar desde la carpeta backend/
    # --------------------------------------------------
    workingDirectory: backend

    # --------------------------------------------------
    # 2) Instalar requisitos Python (incluye uvicorn)
    # --------------------------------------------------
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt

    # --------------------------------------------------
    # 3) Arrancar Uvicorn apuntando a main:app (dentro de backend/)
    #    - Uso de comillas dobles para asegurar expansión de $PORT
    # --------------------------------------------------
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"

    # --------------------------------------------------
    # Healthcheck para comprobar que "/" responde algo
    # --------------------------------------------------
    healthCheckPath: /
