# render.yaml

services:
  # 1) API FastAPI (deploy desde la raíz)
  - type: web
    name: optimizacion-inventario-api
    env: python
    plan: free
    branch: main

    # Instala deps desde backend/requirements.txt
    buildCommand: |
      pip install --upgrade pip
      pip install -r backend/requirements.txt

    # Arranca uvicorn apuntando al módulo backend.main
    # (se ejecuta en la raíz, así Python ve model_utils.py también)
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT

    healthCheckPath: /

  # 2) Frontend estático (serve React/HTML/CSS)
  - type: static
    name: optimizacion-inventario-frontend
    branch: main

    staticPublishPath: frontend/src
    buildCommand: echo "No build needed"
    envVars:
      - key: RENDER_REDIRECT_ROOT
        value: "true"

    # Para Single-Page-Apps, redirigir 404 a index.html
    envVars:
      - key: RENDER_REDIRECT_ROOT
        value: "true"
